[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev --no-interaction && npm ci && npm run build"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
pkgs = ["php83", "php83Packages.composer", "nodejs-22_x"]

